[package]
name = "model"
version = "0.1.0"
edition = "2024"
publish = false

[features]
integration-tests = []

[dependencies]
kovi.workspace = true
reqwest.workspace = true
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
thiserror.workspace = true
sysinfo = "0.39.6"
chrono.workspace = true
chrono-tz.workspace = true
redis.workspace = true
anyhow = {version = "1.0.98"}
base64 = "0.23"
config = "0.15.15"
rand = "0.10"
rmcp.workspace = true
scraper.workspace = true
sha2 = "0.11"
sqlx-core.workspace = true
sqlx-postgres.workspace = true
url.workspace = true
uuid.workspace = true
unicode-properties = "0.1.4"
yunxi-core.workspace = true
